/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fvgprinc.app.testreadxmlfile;

import java.net.URL;

/**
 *
 * @author garfi
 */
public class JFrmPrincApp extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincApp
     */
    public JFrmPrincApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButTest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaOutput = new javax.swing.JTextArea();
        jButTest2 = new javax.swing.JButton();
        jButTest3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButTest.setText("Test");
        jButTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButTestActionPerformed(evt);
            }
        });

        jTxtAreaOutput.setColumns(20);
        jTxtAreaOutput.setRows(5);
        jScrollPane1.setViewportView(jTxtAreaOutput);

        jButTest2.setText("Test 2");
        jButTest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButTest2ActionPerformed(evt);
            }
        });

        jButTest3.setText("Test 3");
        jButTest3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButTest3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButTest)
                        .addGap(18, 18, 18)
                        .addComponent(jButTest2)
                        .addGap(28, 28, 28)
                        .addComponent(jButTest3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButTest)
                    .addComponent(jButTest2)
                    .addComponent(jButTest3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButTestActionPerformed
        URL res = null;
        String fname;
        Class c = null;

        // c = this.getClass();
        ClassLoader loader = Thread.currentThread().getContextClassLoader();

        //   testFile
        //fname = "testFile.xml";
        fname = "testFile.xml";
        // res = c.getResource(fname);
        res = loader.getResource(fname);
        if (res == null) {
            jTxtAreaOutput.setText("File not found");
        } else {
            jTxtAreaOutput.setText("Archivo Encontrado...!!!!!");
        }

    }//GEN-LAST:event_jButTestActionPerformed

    private void jButTest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButTest2ActionPerformed
        //  com.fvgprinc.app.testreadxmlfile.resources
        String fname = "/com/fvgprinc/app/testreadxmlfile/resources/testFile.xml";
        String lexeme = "<%lexeme>";
        String resultado = "Archivo " + lexeme + " encontrado!!!!!";
        //String fname = "com.fvgprinc.app.testreadxmlfile.resources.testFile.xml";
        URL configURL = getClass().getResource(fname);
        if (configURL != null) {
            resultado = resultado.replaceAll(lexeme, "");
        } else {
            resultado = resultado.replaceAll(lexeme, "NO");
        }
        jTxtAreaOutput.setText(resultado);
    }//GEN-LAST:event_jButTest2ActionPerformed

    private void jButTest3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButTest3ActionPerformed
        String fname = "testFile.xml";
        String lexeme = "<%lexeme>";
        String resultado = "Archivo " + lexeme + " encontrado!!!!!";
        fname = "images/Experiment.png";
        //String fname = "com.fvgprinc.app.testreadxmlfile.resources.testFile.xml";
        //URL configURL =    getClass().getResource(fname);
        URL configURL = this.getClass().getClassLoader().getResource(fname);
        if (configURL != null) {
            resultado = resultado.replaceAll(lexeme, "");
        } else {
            resultado = resultado.replaceAll(lexeme, "NO");
        }
        jTxtAreaOutput.setText(resultado);
        // JOptionPane.showMessageDialog(null, msgs);

    }//GEN-LAST:event_jButTest3ActionPerformed

    /**
     * @param args the command line arguments Esto es una prueba
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrmPrincApp jfrm = new JFrmPrincApp();
                jfrm.setLocationRelativeTo(null);
                jfrm.setVisible(true);
                // new JFrmPrincApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButTest;
    private javax.swing.JButton jButTest2;
    private javax.swing.JButton jButTest3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtAreaOutput;
    // End of variables declaration//GEN-END:variables
}
